### ISSUE TITLE
如何添加自定义按钮？

### ISSUE THREAD

**Issue by zxhycxq** [guangqiang-liu/react-navigation-demo#1]
android - react native 中如何实现 自定义按钮 -
![image](https://user-images.githubusercontent.com/11674203/34406936-ade76c8c-ebf6-11e7-9ff7-19b4f170cc9c.png)

博主遇到过吗？我自己写的会被截断（超出的部分）。谢谢了

**Comment by guangqiang-liu** [comment]
自定义按钮，你直接重写导航自带的返回按钮的点击事件就ok了是啊，我的简书中对navigation的使用提供有相应的示例Demo,里面有处理自定义返回按钮场景的，如果还是不行的画，可以加我的交流群，在群里交流提问。


------------------ 原始邮件 ------------------
发件人: "HelloWorld"<notifications@github.com>;
发送时间: 2018年3月16日(星期五) 上午10:10
收件人: "guangqiang-liu/react-navigation-demo"<react-navigation-demo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [guangqiang-liu/react-navigation-demo] 如何添加自定义按钮？ (#1)




Closed #1.
